### ISSUE TITLE
Erro ao tentar enviar e-mail

### ISSUE THREAD

**Issue by c0destep** [aplus-framework/email#1]
realizei alguns testes na hospedagem, mas parece não funcionar corretamente. E esta me retornado o seguintes erros:
```
stream_socket_enable_crypto(): SSL: Broken pipe
```
```
Send of 12 bytes failed with errno=32 Broken pipe
```

**Comment by natanfelles** [comment]
Por favor, certifique-se de que está usando a porta certa (25, 465 ou 587) e se o `crlf` é `"\r\n"` ou `"\n"`.

Se não funcionar, poderia me enviar dados de acesso para testar nessa hospedagem? natanfelles@gmail.com

**Comment by c0destep** [comment]
> Por favor, certifique-se de que está usando a porta certa (25, 465 ou 587) e se o `crlf` é `"\r\n"` ou `"\n"`.
> 
> Se não funcionar, poderia me enviar dados de acesso para testar nessa hospedagem? [natanfelles@gmail.com](mailto:natanfelles@gmail.com)

Quais dados você precisa?

**Comment by natanfelles** [comment]
Informações da [Mailer Connection](https://docs.aplus-framework.com/guides/libraries/email/index.html#mailer-connection).

**Comment by c0destep** [comment]
Encaminhei no seu e-mail

**Comment by natanfelles** [comment]
Olá, camarada!

Basta colocar a porta 587 ([Porta TLS](https://www.hostinger.com.br/tutoriais/portas-pop3-smtp-e-imap), também conhecida como SMTP TLS) que vai funcionar! :smiley: 

<sub>* Não esqueça de mudar a senha.</sub>

**Comment by c0destep** [comment]
Obrigado pelo suporte :smiley:
